spring:
  config:
    import: aws-parameterstore:/member/prod/

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  team-name: ${team-name}